INSERT INTO TBL_USER(USER_ID, LOGIN_ID, PASSWORD, GENDER, EMAIL, ADDRESS, ADDRESS_DETAIL, ZIPCODE)
VALUES (SEQ_USER.nextval, 'aaa', '1234', 'M', 'aaa@naver.com', 'test', 'test', '12345');

INSERT INTO TBL_BOARD(BOARD_ID, TITLE, CONTENT, USER_ID)
VALUES (SEQ_BOARD.nextval, 'TEST', 'TEST', 1);